#!/bin/sh
#
# Copyright © 2017 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

changes="$1"

set -e

cat <<'WARN'

Warning: Do NOT upload packages to the security upload queue
(oldstable-security, stable-security, etc.) without prior authorization
from the Debian security team. For more information, please read:

  <https://www.debian.org/doc/developers-reference/pkgs.html#bug-security>

If you have been authorized, you can either disable this hook, or reply to
the following prompt with the exact text presented within parenthesis.

WARN

auth='Yes, I am authorized'

read -p "Are you authorized to upload ($auth)? " prompt

if [ "$prompt" = "$auth" ]; then
  echo "Authorized, proceeding with the upload."
  echo
else
  echo "Not authorized, aborting the upload." >&2
  echo
  exit 1
fi

# XXX: Backwards compatibility for configurations that use a scalar instead
# of a list ref for the preupload hooks.
if [ "$DUPLOAD_PREUPLOAD_HOOK_SCALAR" = "yes" ]; then
  # Chain the OpenPGP check, so that we can override the default global hook.
  /usr/share/dupload/openpgp-check "$changes"
fi
