#!/usr/bin/perl
#
# Copyright © 2023 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

use strict;
use warnings;

use Time::Piece;
use Time::Seconds;

# https://ftp-master.debian.org/dinstall.html
my $start = '01:52';
my $every = 6 * ONE_HOUR;

my $now = localtime;
my $t = $now->truncate(to => 'day') +
        $now->tzoffset +
        Time::Piece->strptime($start, '%H:%M')->epoch;

for (my $iter = 0; ; $iter++) {
    my $it = $t + ($iter * $every);
    my $delta = $it - $now->epoch;

    if ($delta->epoch > 0) {
        print "\n";
        printf "Next Debian dinstall run is at: %s\n", $it->cdate;
        exit 0;
    }
}

1;
