#!/bin/sh
#
# Copyright © 2017, 2019, 2021 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -e

cat <<'WARN'

Warning: Do NOT upload packages to the security upload queue
(oldstable-security, stable-security, etc.) without prior authorization
from the Debian security team. For more information, please read:

  <https://www.debian.org/doc/developers-reference/pkgs.html#bug-security>

Note: If you have been authorized, you can either disable this hook in
the configuration file, skip it via --skip-hooks or the one-off environment
variable DUPLOAD_SKIP_HOOKS, or reply to the following prompt with the
exact text presented within parenthesis.

WARN

auth='Yes, I am authorized'

printf "Are you authorized to upload (%s)? " "$auth"
read -r prompt

if [ "$prompt" = "$auth" ]; then
  echo "Authorized, proceeding with the upload."
  echo
else
  echo "Not authorized, aborting the upload." >&2
  echo
  exit 1
fi
